services:
  app:
    image: bloglist-frontend
    build: ./frontend
    container_name: bloglist-frontend
    ports:
      - 5173:80
    depends_on:
      - server

  server:
    image: bloglist-backend
    volumes:
      - /usr/src/app/node_modules
    environment:
      POSTGRES_URL: postgres://root:example@postgres:5432/bloglist_db
      PORT: 3001
      SECRET: secret
    build: ./backend
    container_name: bloglist-backend
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/18/docker

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bloglist_db
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
      - postgres
volumes:
  pgdata:
